import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Match the legacy WordPress URL shape (every page has a trailing slash)
  // so existing SEO equity / inbound links keep working.
  trailingSlash: true,
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "quadbiketourism.com", pathname: "/wp-content/uploads/**" },
      { protocol: "https", hostname: "www.quadbiketourism.com", pathname: "/wp-content/uploads/**" },
      { protocol: "https", hostname: "**.public.blob.vercel-storage.com" },
    ],
  },
  async redirects() {
    return [
      // Existing blog path normalisation
      { source: "/blogs", destination: "/blog", permanent: true },
      { source: "/blogs/:slug", destination: "/blog/:slug", permanent: true },

      // A) Legacy root-level blog posts -> /blog/<slug> (55 posts, explicit per slug)
      { source: "/what-dress-to-wear-for-quad-biking-in-dubai", destination: "/blog/what-dress-to-wear-for-quad-biking-in-dubai", permanent: true },
      { source: "/atv-vs-quad-bike-key-differences-every-rider-should-know", destination: "/blog/atv-vs-quad-bike-key-differences-every-rider-should-know", permanent: true },
      { source: "/5-best-desert-adventure-activities-for-tourists-visiting-dubai", destination: "/blog/5-best-desert-adventure-activities-for-tourists-visiting-dubai", permanent: true },
      { source: "/top-desert-locations-for-quad-biking-in-dubai", destination: "/blog/top-desert-locations-for-quad-biking-in-dubai", permanent: true },
      { source: "/how-much-does-it-cost-to-quad-biking-in-dubai", destination: "/blog/how-much-does-it-cost-to-quad-biking-in-dubai", permanent: true },
      { source: "/quad-biking-dubai-guide-a-thrilling-desert-adventure-in-2025", destination: "/blog/quad-biking-dubai-guide-a-thrilling-desert-adventure-in-2025", permanent: true },
      { source: "/quad-bike-summer-adventure-in-dubai", destination: "/blog/quad-bike-summer-adventure-in-dubai", permanent: true },
      { source: "/thrilling-dune-bashing-in-dubai-in-summer", destination: "/blog/thrilling-dune-bashing-in-dubai-in-summer", permanent: true },
      { source: "/explore-dubais-sand-dunes-by-quad-bike", destination: "/blog/explore-dubais-sand-dunes-by-quad-bike", permanent: true },
      { source: "/what-is-quad-biking-dubai-tour-around-the-world", destination: "/blog/what-is-quad-biking-dubai-tour-around-the-world", permanent: true },
      { source: "/when-is-the-best-time-for-quad-biking-in-dubai-a-seasonal-guide", destination: "/blog/when-is-the-best-time-for-quad-biking-in-dubai-a-seasonal-guide", permanent: true },
      { source: "/what-is-a-morning-desert-safari-tour", destination: "/blog/what-is-a-morning-desert-safari-tour", permanent: true },
      { source: "/what-is-included-in-a-desert-safari-tour", destination: "/blog/what-is-included-in-a-desert-safari-tour", permanent: true },
      { source: "/how-to-explore-the-dubai-desert-safari", destination: "/blog/how-to-explore-the-dubai-desert-safari", permanent: true },
      { source: "/what-is-a-camel-ride-in-the-dubai-desert-safari", destination: "/blog/what-is-a-camel-ride-in-the-dubai-desert-safari", permanent: true },
      { source: "/how-to-visit-desert-safari-dubai-adventures", destination: "/blog/how-to-visit-desert-safari-dubai-adventures", permanent: true },
      { source: "/how-to-find-the-best-desert-safari-in-dubai", destination: "/blog/how-to-find-the-best-desert-safari-in-dubai", permanent: true },
      { source: "/where-is-the-most-amazing-desert-safari-in-abu-dhabi", destination: "/blog/where-is-the-most-amazing-desert-safari-in-abu-dhabi", permanent: true },
      { source: "/best-quad-bike-rentals-in-sharjah", destination: "/blog/best-quad-bike-rentals-in-sharjah", permanent: true },
      { source: "/guided-quad-bike-tour-in-rak-dunes", destination: "/blog/guided-quad-bike-tour-in-rak-dunes", permanent: true },
      { source: "/how-to-ride-a-quad-bike-safely-as-a-beginner", destination: "/blog/how-to-ride-a-quad-bike-safely-as-a-beginner", permanent: true },
      { source: "/what-is-a-quad-bike-useful-for", destination: "/blog/what-is-a-quad-bike-useful-for", permanent: true },
      { source: "/buggy-rides-dubai-best-4-x-4-desert-safari", destination: "/blog/buggy-rides-dubai-best-4-x-4-desert-safari", permanent: true },
      { source: "/dubai-luxury-tours-adventures", destination: "/blog/dubai-luxury-tours-adventures", permanent: true },
      { source: "/would-i-be-considered-a-biker-if-i-ride-an-atv-quad", destination: "/blog/would-i-be-considered-a-biker-if-i-ride-an-atv-quad", permanent: true },
      { source: "/desert-quad-biking-in-dubai-book-your-adventure-today", destination: "/blog/desert-quad-biking-in-dubai-book-your-adventure-today", permanent: true },
      { source: "/dubai-morning-desert-safari-with-quad-biking-2026", destination: "/blog/dubai-morning-desert-safari-with-quad-biking-2026", permanent: true },
      { source: "/desert-safari-dubai-with-double-seat-quad-bike", destination: "/blog/desert-safari-dubai-with-double-seat-quad-bike", permanent: true },
      { source: "/what-is-unique-about-the-desert-safari-in-the-uae", destination: "/blog/what-is-unique-about-the-desert-safari-in-the-uae", permanent: true },
      { source: "/quad-bike-tour-with-private-pick-up-drop-off", destination: "/blog/quad-bike-tour-with-private-pick-up-drop-off", permanent: true },
      { source: "/the-best-dubai-quad-bike-dune-buggy-tours-2026", destination: "/blog/the-best-dubai-quad-bike-dune-buggy-tours-2026", permanent: true },
      { source: "/buggy-rides-dubai-best-4-x-4-desert-safari-in-desert", destination: "/blog/buggy-rides-dubai-best-4-x-4-desert-safari-in-desert", permanent: true },
      { source: "/book-quad-biking-desert-safari-in-dubai", destination: "/blog/book-quad-biking-desert-safari-in-dubai", permanent: true },
      { source: "/quad-bike-safari-camels-camp-with-bbq-dinner", destination: "/blog/quad-bike-safari-camels-camp-with-bbq-dinner", permanent: true },
      { source: "/30-minute-quad-biking-adventure-for-one-in-abu-dhabi", destination: "/blog/30-minute-quad-biking-adventure-for-one-in-abu-dhabi", permanent: true },
      { source: "/desert-adventure-club-home-desert-adventure-club", destination: "/blog/desert-adventure-club-home-desert-adventure-club", permanent: true },
      { source: "/1-hour-afternoon-quad-bike-tour-dubai", destination: "/blog/1-hour-afternoon-quad-bike-tour-dubai", permanent: true },
      { source: "/expert-tips-for-a-successful-quad-biking-dubai-tour", destination: "/blog/expert-tips-for-a-successful-quad-biking-dubai-tour", permanent: true },
      { source: "/what-are-the-activities-to-do-in-the-desert-safari-dubai-tour", destination: "/blog/what-are-the-activities-to-do-in-the-desert-safari-dubai-tour", permanent: true },
      { source: "/60-minute-quad-bike-tour-for-one-with-refreshments", destination: "/blog/60-minute-quad-bike-tour-for-one-with-refreshments", permanent: true },
      { source: "/quad-bikes-ride-in-dubai-hatta-tour-2", destination: "/blog/quad-bikes-ride-in-dubai-hatta-tour-2", permanent: true },
      { source: "/desert-wildlife-you-can-spot-while-quad-biking-in-dubai", destination: "/blog/desert-wildlife-you-can-spot-while-quad-biking-in-dubai", permanent: true },
      { source: "/what-helmets-safety-gear-do-dubai-quad-bike-operators-provide", destination: "/blog/what-helmets-safety-gear-do-dubai-quad-bike-operators-provide", permanent: true },
      { source: "/how-dubai-desert-safari-has-evolved-from-a-local-tradition-to-a-global-attraction", destination: "/blog/how-dubai-desert-safari-has-evolved-from-a-local-tradition-to-a-global-attraction", permanent: true },
      { source: "/can-you-quad-bike-in-dubai-with-a-bad-back-medical-conditions-restrictions", destination: "/blog/can-you-quad-bike-in-dubai-with-a-bad-back-medical-conditions-restrictions", permanent: true },
      { source: "/motion-sickness-during-dune-bashing-how-to-prevent-it-before-your-safari", destination: "/blog/motion-sickness-during-dune-bashing-how-to-prevent-it-before-your-safari", permanent: true },
      { source: "/how-to-live-stream-your-quad-biking-adventure-in-dubai-on-social-media", destination: "/blog/how-to-live-stream-your-quad-biking-adventure-in-dubai-on-social-media", permanent: true },
      { source: "/what-to-pack-in-your-bag-for-a-dubai-desert-safari-with-quad-biking", destination: "/blog/what-to-pack-in-your-bag-for-a-dubai-desert-safari-with-quad-biking", permanent: true },
      { source: "/how-quad-bike-operators-inspect-service-bikes-before-each-desert-ride", destination: "/blog/how-quad-bike-operators-inspect-service-bikes-before-each-desert-ride", permanent: true },
      { source: "/is-desert-safari-tourism-in-dubai-sustainable-an-honest-assessment", destination: "/blog/is-desert-safari-tourism-in-dubai-sustainable-an-honest-assessment", permanent: true },
      { source: "/is-dubai-desert-safari-worth-it-in-2026-pros-cons", destination: "/blog/is-dubai-desert-safari-worth-it-in-2026-pros-cons", permanent: true },
      { source: "/shared-group-desert-safari-vs-fully-private-a-complete-value-comparison", destination: "/blog/shared-group-desert-safari-vs-fully-private-a-complete-value-comparison", permanent: true },
      { source: "/what-to-do-after-a-desert-safari-in-dubai-the-best-evening-plans", destination: "/blog/what-to-do-after-a-desert-safari-in-dubai-the-best-evening-plans", permanent: true },
      { source: "/sun-protection-for-desert-safari-in-dubai-sunscreen-hats-skin-safety-tips", destination: "/blog/sun-protection-for-desert-safari-in-dubai-sunscreen-hats-skin-safety-tips", permanent: true },
      { source: "/hydration-guide-for-quad-biking-in-dubai-essential-fluid-intake-for-desert-riding", destination: "/blog/hydration-guide-for-quad-biking-in-dubai-essential-fluid-intake-for-desert-riding", permanent: true },

      // B) Legacy WooCommerce product URLs -> new category paths (24 products)
      { source: "/product/desert-quad-bike-90cc", destination: "/quad-bikes/desert-quad-bike-90cc", permanent: true },
      { source: "/product/desert-quad-bike-150cc", destination: "/quad-bikes/desert-quad-bike-150cc", permanent: true },
      { source: "/product/desert-quad-bike-250cc", destination: "/quad-bikes/desert-quad-bike-250cc", permanent: true },
      { source: "/product/desert-quad-bike-450cc", destination: "/quad-bikes/desert-quad-bike-450cc", permanent: true },
      { source: "/product/ktm-dirt-bikes-450cc", destination: "/quad-bikes/ktm-dirt-bikes-450cc", permanent: true },
      { source: "/product/polaris-rzr-1000cc", destination: "/buggy-tours/polaris-rzr-1000cc", permanent: true },
      { source: "/product/polaris-rzr-1000cc-2-seater", destination: "/buggy-tours/polaris-rzr-1000cc-2-seater", permanent: true },
      { source: "/product/polaris-rzr-1000cc-4-seater", destination: "/buggy-tours/polaris-rzr-1000cc-4-seater", permanent: true },
      { source: "/product/polaris-rzr-turbo-1800cc-4-seater", destination: "/buggy-tours/polaris-rzr-turbo-1800cc-4-seater", permanent: true },
      { source: "/product/canam-maverick-1700cc-2-seater", destination: "/buggy-tours/canam-maverick-1700cc-2-seater", permanent: true },
      { source: "/product/canam-maverick-1700cc-4-seater", destination: "/buggy-tours/canam-maverick-1700cc-4-seater", permanent: true },
      { source: "/product/custom-power-buggy-3000cc-2-seater", destination: "/buggy-tours/custom-power-buggy-3000cc-2-seater", permanent: true },
      { source: "/product/abu-dhabi-city-tour", destination: "/city-tours/abu-dhabi-city-tour", permanent: true },
      { source: "/product/dubai-city-tour", destination: "/city-tours/dubai-city-tour", permanent: true },
      { source: "/product/hatta-mountain-tour", destination: "/city-tours/hatta-mountain-tour", permanent: true },
      { source: "/product/parks-gardens-tour", destination: "/city-tours/parks-gardens-tour", permanent: true },
      { source: "/product/yamaha-jet-ski", destination: "/water-sports/yamaha-jet-ski", permanent: true },
      { source: "/product/jet-car-corvette", destination: "/water-sports/jet-car-corvette", permanent: true },
      { source: "/product/banana-boat", destination: "/water-sports/banana-boat", permanent: true },
      { source: "/product/flyboard-in-dubai", destination: "/water-sports/flyboard-in-dubai", permanent: true },
      { source: "/product/parasailing", destination: "/water-sports/parasailing", permanent: true },
      { source: "/product/evening-desert-safari", destination: "/desert-safari/evening-desert-safari", permanent: true },
      { source: "/product/morning-desert-safari", destination: "/desert-safari/morning-desert-safari", permanent: true },
      { source: "/product/afternoon-desert-safari", destination: "/desert-safari/afternoon-desert-safari", permanent: true },

      // C) Legacy WooCommerce taxonomy / system pages -> closest new equivalent
      { source: "/product-category/quad-bike", destination: "/quad-bikes", permanent: true },
      { source: "/product-category/dune-buggy-tours", destination: "/buggy-tours", permanent: true },
      { source: "/product-category/water-sports", destination: "/water-sports", permanent: true },
      { source: "/product-category/desert-safari-tour", destination: "/desert-safari", permanent: true },
      { source: "/shop", destination: "/tours", permanent: true },
    ];
  },
};

export default nextConfig;
